name: Obowiązki dzieci
version: "0.4.1"
slug: family_reward_planner
description: Planner obowiązków, gwiazdek, kuponów i nagród dla dzieci.
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8099
ingress_entry: /child
homeassistant_api: true
panel_icon: mdi:star-face
panel_title: Obowiązki dzieci
panel_admin: false
map:
  - type: addon_config
    read_only: false
options:
  child_module_title: Obowiązki dzieci
  parent_module_title: Panel rodzica
schema:
  child_module_title: str
  parent_module_title: str
